name: http2
version: 2.2.0
description: A HTTP/2 implementation in Dart. Fork form Http/2-2.2.0 to support Ohos.
repository: https://github.com/whf881211/http2

environment:
  sdk: '>=2.17.0 <3.0.0'

dev_dependencies:
  build_runner: ^2.3.0
  lints: ^2.0.0
  mockito: ^5.3.2
  test: ^1.21.4
